name: "Blaze-Expression CI"
on: [push, pull_request]
env:
  MAVEN_SKIP_RC: true
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - jdk: 8
          - jdk: 11
          - jdk: 17
          - jdk: 18
          - jdk: 19
          - jdk: 17
            build-jdk: 17
          - jdk: 18
            build-jdk: 18
          - jdk: 19
            build-jdk: 19
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set env
        run: echo "JDK8_HOME=$(echo $JAVA_HOME)" >> $GITHUB_ENV
      - name: Set up Requested JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk == 19 && '19-ea' || matrix.jdk }}
          distribution: 'temurin'
      - name: Setup CA certificates
        if: ${{ matrix.jdk != 8 }}
        run: |
          rm $JAVA_HOME/lib/security/cacerts
          cp $JDK8_HOME/jre/lib/security/cacerts $JAVA_HOME/lib/security/cacerts

      - name: Get year/month for cache key
        id: get-date
        run: |
          echo "::set-output name=yearmonth::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Cache Maven local repository
        uses: actions/cache@v4
        id: cache-maven
        with:
          path: |
            ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-localrepo-${{ steps.get-date.outputs.yearmonth }}
      - name: Set up Maven
        run: ./mvnw -v

      - name: Run build script
        env:
          JDK8_HOME: ${{ env.JDK8_HOME }}
          JDK: ${{ matrix.jdk }}
          BUILD_JDK: ${{ matrix.build-jdk }}
        run: ./ci/build-github.sh
        shell: bash

      - name: Upload test reports (if Maven failed)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports-jdk${{ matrix.jdk }}-build-jdk${{ matrix.build-jdk }}
          path: './**/*-reports/'

      - name: Omit produced artifacts from build cache
        run: ./ci/before-cache.sh